# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Waqas Bin Hamed"
email: waqasbinhamed@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal website of Waqas Bin Hamed.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://waqasbinhamed.github.io" # the base hostname & protocol for your site
twitter_username: # username
github_username: waqasbinhamed
minimal_mistakes_skin: default
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:title/
# Disable pagination since we're not using posts
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache

author:
  name   : "Waqas Bin Hamed"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Data Scientist | MMath Computational Mathematics"
  location: "Toronto, ON"
  email: "waqasbinhamed@gmail.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:waqasbinhamed@gmail.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://waqasbinhamed.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/waqasbinhamed"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/yourprofile"
    # - label: "Google Scholar"
    #   icon: "fas fa-fw fa-graduation-cap"
    #   url: "https://scholar.google.com/citations?user=yourprofile"
    # - label: "ORCID"
    #   icon: "fab fa-fw fa-orcid"
    #   url: "https://orcid.org/0000-0000-0000-0000"

footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:waqas@example.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/waqasbinhamed"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/yourprofile"

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts (disabled for academic site)
  # - scope:
  #     path: ""
  #     type: posts
  #   values:
  #     layout: single
  #     author_profile: true

# Disable blog-related archives since we're not using posts
# category_archive:
#   type: liquid
#   path: /categories/
# tag_archive:
#   type: liquid
#   path: /tags/
